title: "FREEBASSEL"
hashtag: "#freebassel5years"
tagline: "Campaign to FREE Bassel Khartabil"
exclude: [README.md, LICENSE.md, designs, Gemfile, Gemfile.lock, config, get_supporters_data.rb]

permalink: /campaign/:categories/:year/:month/:day/:title/
future: true

name: FREEBASSEL
description: "We free loved technology innovator, Bassel Khartabil, detained since March 15, 2012, disappeared Oct 23, 2015."
url: http://freebassel.org
repository: freebassel/freebassel.org

keywords: ['freebassel', 'basselkhartabil ', 'basselsafadi', 'bassel', 'whereisbassel', 'syria', 'damascus', 'creativecommons', 'freeculture', 'disappeared']

email: info@freebassel.org
twitter: freebassel
facebook: freebassel
instagram: freebassel
birthday: "1981-05-22"

languages :
  en: English
  ar: Arabic

instafeed:
  tag: 'freebassel'
  client_id: '515a7d6587b249f18c9a855868e0ac1b'
  captions: true
  limit: '20'
  refresh: '60000'

gems:
  - jekyll-sitemap
  - jekyll-github-metadata
