GOOGLE_CLIENT_ID = "XXXXXXXXXXXXXXXXXXXXX"

GOOGLE_CLIENT_SECRET = "XXXXXXXXXXXXXXXXX"

GOOGLE_SPREADSHEET_KEY = "XXXXXXXXXXXXXXX"
       
CHANGE_ORG_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'